using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ThirdPersonCamera : MonoBehaviour
{
    [Header("타겟 설정")]
    public Transform target;

    [Header("카메라 거리 설정")]
    public float distance = 8.0f;
    public float height = 5.0f;

    [Header("마우스 설정")]
    public float mouseSensivitiy = 2.0f;
    public float minVecticalAngle = -30.0f;
    public float maxvecticalAngle = 60.0f;

    [Header("부드러움 설정")]
    public float positionSmoothTime = 0.2f;
    public float rotationSmoothTime = 0.1f;

    //회전 각도
    private float horizontalAngle = 0.0f;
    private float verticalAngle = 0.0f;

    //움직임용 변수
    private Vector3 currentVelocity;
    private Vector3 currentPosition;
    private Quaternion currentRotation;


    // Start is called before the first frame update
    void Start()
    {
        if (target == null)
        {
            GameObject player = GameObject.FindGameObjectWithTag("Player");
            if (player != null)
                target = player.transform;
        }
        //초기 위치 회전 설정
        currentPosition = transform.position;
        currentRotation = transform.rotation;
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKeyDown(KeyCode.Escape)) { ToggleCursor(); }                //ESC 로 커서 토글
    }

    void LateUpdate()
    {
        if (target == null) return;
        HandleMouseInput();
        UpdateCameraSmooth();
    }

    void HandleMouseInput()                     //마우스 입력으로 화면 처리 함수
    {
        //커서가 잠겨 있을때만 마우스 입력 처리
        if (Cursor.lockState != CursorLockMode.Locked) return;

        float mouseX = Input.GetAxis("Mouse X") * mouseSensivitiy;
        float mouseY = Input.GetAxis("Mouse Y") * mouseSensivitiy;

        horizontalAngle += mouseX;
        verticalAngle -= mouseY;

        verticalAngle = Mathf.Clamp(verticalAngle,minVecticalAngle,maxvecticalAngle);
    }

    void UpdateCameraSmooth()               //카메라 목표 위치 계산 하는 함수
    {
        //목표 위치 계산
        Quaternion rotation = Quaternion.Euler(verticalAngle, horizontalAngle, 0);
        Vector3 rotateOffset = rotation * new Vector3(0, height , -distance);
        Vector3 targetPosition = target.position + rotateOffset;

        //목표 회전 계산
        Vector3 looktarget = target.position + Vector3.up * height;
        Quaternion targetRotation = Quaternion.LookRotation(looktarget - targetPosition);

        //부드럽게 이동
        currentPosition = Vector3.SmoothDamp(currentPosition, targetPosition, ref currentVelocity, positionSmoothTime);

        //부드럽게 회전
        currentRotation = Quaternion.Slerp(currentRotation,targetRotation,Time.deltaTime / rotationSmoothTime);

        //값 적용
        transform.position = currentPosition;
        transform.rotation = currentRotation;   
    }

    void ToggleCursor()
    {
        if(Cursor.lockState == CursorLockMode.Locked)
        {
            Cursor.lockState = CursorLockMode.None;
            Cursor.visible = true;


        }
        else
        {
            Cursor.lockState= CursorLockMode.Locked;
            Cursor.visible = false;
        }
    }
}
